
import os, sys, gc, warnings
import pandas as pd
import numpy as np
import seaborn as sns
from collections import Counter
from nltk.tokenize import word_tokenize
import nltk
import re
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')

file_path = 'train.norm.csv'
df = pd.read_csv(file_path)

df.columns = ['ColumnWithHeader']

non_standard_word = {
    'n8':'night',
    'gn':'goodnight',
    '2nite': 'tonight',
    'thx': 'thanks',
    'bday': 'birthday',
    'gr8': 'great',
    'plz': 'please',
    'lil': 'little',
    'cuz': 'because',
    'gonna': 'going to',
    'gimme': 'give me',
    'wanna': 'want to',
    'luv': 'love',
    'r': 'are',
    'u': 'you',
    'thru': 'through',
    'nite': 'night',
    'cya': 'see you',
    'ttyl': 'talk to you later',
    'omg': 'oh my god',
    'lol': 'laughing out loud',
    'btw': 'by the way',
    'fyi': 'for your information',
    'brb': 'be right back',
    'gtg': 'got to go',
    'imho': 'in my humble opinion',
    'idk': "I don't know",
    'smh': 'shaking my head',
    'lemme': 'let me',
    'hav': 'have',
    'lmao': 'laughing my [expletive] off',
    'gimme': 'give me',
    'idc': "I don't care",
    'plz': 'please',
    'yolo': 'you only live once',
    'fomo': 'fear of missing out',
    'selfie': 'self-portrait',
    'hangry': 'hungry + angry',
    'chillax': 'chill + relax',
    'totes': 'totally',
    'fwiw': "for what it's worth",
    'icymi': 'in case you missed it',
    'ama': 'ask me anything',
    'tmi': 'too much information',
    'tldr': "too long; didn't read",
    'irl': 'in real life',
    'fotd': 'face of the day',
    'smh': 'shaking my head',
    'afk': 'away from keyboard',
    'hmu': 'hit me up',
    'yass': 'yes',
    'fam': 'family',
    'bae': 'before anyone else',
    'lit': 'amazing or cool',
    'nsfw': 'not safe for work',
    'ootd': 'outfit of the day',
    'rofl': 'rolling on the floor laughing',
    'tgif': "thank goodness it's Friday",
    'imo': 'in my opinion',
    'irl': 'in real life',
    'btw': 'by the way',
    'meh': 'indifferent or unimpressed',
    'totes': 'totally',
    'bruh': 'brother or friend',
    'ship': 'relationship',
    'tbh': 'to be honest',
    'wut': 'what',
    'fwiw': "for what it's worth",
    'h8r': 'hater',
    'imo': 'in my opinion',
    'jelly': 'jealous',
    'kthxbye': 'okay, thanks, goodbye',
    'lemme': 'let me',
    'noob': 'newbie',
    'obvi': 'obviously',
    'peeps': 'people',
    'qt': 'cute',
    'rly': 'really',
    'srsly': 'seriously',
    'tho': 'though',
    'u': 'you',
    'v': 'very',
    'wut': 'what',
    'xoxo': 'hugs and kisses',
    'yolo': 'you only live once',
    'zomg': 'oh my god',
    'vlog': 'video blog',
    'bffl': 'best friends for life',
    'cya': 'see ya',
    'fam': 'family',
    'gratz': 'congratulations',
    'hav': 'have',
    'icymi': 'in case you missed it',
    'jk': 'just kidding',
    'l8r': 'later',
    'meh': 'meh',
    'nvm': 'never mind',
    'omg': 'oh my goodness',
    'ppl': 'people',
    'rofl': 'rolling on the floor laughing',
    'sry': 'sorry',
    'tba': 'to be announced',
    'ttyl': 'talk to you later',
    'w8': 'wait',
    'yass': 'yes',
    'btw': 'by the way',
    'ftw': 'for the win',
    'afk': 'away from keyboard',
    'bday': 'birthday',
    'ctfu': 'cracking the [expletive] up',
    'fml': '[expletive] my life',
    'gtg': 'got to go',
    'hmu': 'hit me up',
    'idc': "I don't care",
    'j/k': 'just kidding',
    'kudos': 'congratulations',
    'lmao': 'laughing my [expletive] off',
    'nbd': 'no big deal',
    'omw': 'on my way',
    'pov': 'point of view',
    'qap': 'quick as possible',
    'smh': 'shaking my head',
    'tgif': "thank goodness it's Friday",
    'vibe': 'atmosphere or mood',
    'wcw': 'woman crush Wednesday',
    'yolo': 'you only live once',
    'zomg': 'oh my goodness',
    'btw': 'by the way',
    'ICYMI': 'in case you missed it',
    'TL;DR': "too long; didn't read",
    'FOMO': 'fear of missing out',
    'IRL': 'in real life',
    'DM': 'direct message',
    'BRB': 'be right back',
    'SMH': 'shaking my head',
    'TMI': 'too much information',
    'IMO': 'in my opinion',
    'TBH': 'to be honest',
    'NSFW': 'not safe for work',
    'LOL': 'laughing out loud',
    'OMG': 'oh my god',
    'ROFL': 'rolling on the floor laughing',
    'IDK': "I don't know",
    'AFAIK': 'as far as I know',
    'TTYL': 'talk to you later',
    'FWIW': "for what it's worth",
    'FYI': 'for your information',
    'IMO': 'in my opinion',
    'ICYMI': 'in case you missed it',
    'BFF': 'best friends forever',
    'DIY': 'do it yourself',
    'ETA': 'estimated time of arrival',
    'FWIW': "for what it's worth",
    'GTG': 'got to go',
    'ICYMI': 'in case you missed it',
    'JK': 'just kidding',
    'LMAO': 'laughing my [expletive] off',
    'NVM': 'never mind',
    'OMG': 'oh my goodness',
    'Q&A': 'question and answer',
    'ROFL': 'rolling on the floor laughing',
    'SOS': 'save our souls',
    'TTYL': 'talk to you later',
    'YOLO': 'you only live once',
    'BRB': 'be right back',
    'AFAIK': 'as far as I know',
    'AMA': 'ask me anything',
    'Bae': 'before anyone else',
    'CR8': 'create',
    'DM': 'direct message',
    'FB': 'Facebook',
    'GR8': 'great',
    'H8': 'hate',
    'ICYMI': 'in case you missed it',
    'JOMO': 'joy of missing out',
    'K': 'okay',
    'L8R': 'later',
    'MIA': 'missing in action',
    'NBD': 'no big deal',
    'OOTD': 'outfit of the day',
    'PPL': 'people',
    'QOTD': 'quote of the day',
    'SMH': 'shaking my head',
    'TBH': 'to be honest',
    'WCW': 'woman crush Wednesday',
    'YOLO': 'you only live once',
    'AC': 'air conditioning',
    'DIY': 'do it yourself',
    'EOD': 'end of day',
    'FOMO': 'fear of missing out',
    'GTG': 'got to go',
    'ICYMI': 'in case you missed it',
    'J/K': 'just kidding',
    'KPI': 'key performance indicator',
    'L8': 'late',
    '2':'to',
    'dis':'this',
    'wat':'what',
    'MTD': 'month to date',
    'N/A': 'not applicable',
    'OOTO': 'out of the office',
    'PM': 'private message',
    'Q&A': 'question and answer',
    'R&D': 'research and development',
     'SOP': 'standard operating procedure',
    'TGIF': "thank goodness it's Friday",
    'U': 'you',
    'VLOG': 'video blog',
    'WFH': 'work from home',
    'BRB': 'be right back',
    'FAQ': 'frequently asked questions',
    'HBD': 'happy birthday',
    'IRL': 'in real life',
    'JSYK': 'just so you know',
    'LMK': 'let me know',
    'OOTD': 'outfit of the day',
    'POS': 'parent over shoulder',
    'QOTD': 'quote of the day',
    'SMH': 'shaking my head',
    'TBA': 'to be announced',
    'U2': 'you too',
    'WYD': 'what you doing',
    'XOXO': 'hugs and kisses',
    'YOLO': 'you only live once',
    'ZOMG': 'oh my god',
    'ICYMI': 'in case you missed it',
    'NVM': 'never mind',
    'AMA': 'ask me anything',
    'BTW': 'by the way',
    'CBA': "can't be bothered",
    'DND': 'do not disturb',
    'ETA': 'estimated time of arrival',
    'FTW': 'for the win',
    'GG': 'good game',
    'IDC': "I don't care",
    'JOMO': 'joy of missing out',
    'KPI': 'key performance indicator',
    'L8R': 'later',
    'MIA': 'missing in action',
    'NBD': 'no big deal',
    'OFC': 'of course',
    'PM': 'private message',
    'ROFL': 'rolling on the floor laughing',
    'SOS': 'save our souls',
    'TTYL': 'talk to you later',
    'WTH': 'what the heck',
    'XYZ': 'examine your zipper',
    'Zzz': 'sleeping or bored',
    'B2B': 'business to business',
    'CIR': 'cumulative incidence rate',
    'DIY': 'do it yourself',
    'EOF': 'end of file',
    'F2F': 'face to face',
    'G2G': 'got to go',
    'HBY': 'how about you',
    'IIRC': 'if I recall correctly',
    'JFYI': 'just for your information',
    'K9': 'canine',
    'LOL': 'laughing out loud',
    'MVP': 'most valuable player',
    'OMW': 'on my way',
    'PPL': 'people',
    'QWERTY': 'the first six letters on a standard keyboard',
    'SMH': 'shaking my head',
    'TMI': 'too much information',
    'UV': 'ultraviolet',
    'WDYM': 'what do you mean',
    'XYZ': 'examine your zipper',
    'Zzz': 'sleeping or bored',
    'BRB': 'be right back',
    'CIR': 'circulating',
    'DIY': 'do it yourself',
    'ETA': 'estimated time of arrival',
    'FAQ': 'frequently asked questions',
    'GR8': 'great',
    'ICYMI': 'in case you missed it',
    'JK': 'just kidding',
    'Kudos': 'congratulations',
    'L8': 'late',
    'MIA': 'missing in action',
    'NVM': 'never mind',
    'OOTO': 'out of the office',
    'PPL': 'people',
    'QOTD': 'quote of the day',
    'R&D': 'research and development',
    'SOP': 'standard operating procedure',
    'TGIF': "thank goodness it's Friday",
    'U': 'you',
    'VLOG': 'video blog',
    'WFH': 'work from home',
    'XOXO': 'hugs and kisses',
    'YOLO': 'you only live once',
    'ZOMG': 'oh my god',
    'ICYMI': 'in case you missed it',
    'NVM': 'never mind',
    'AC': 'air conditioning',
    'BTW': 'by the way',
    'COB': 'close of business',
    'DND': 'do not disturb',
    'EOD': 'end of day',
    'FYI': 'for your information',
    'GMTA': 'great minds think alike',
    'HBD': 'happy birthday',
    'IDK': "I don't know",
    'JIC': 'just in case',
    'KPI': 'key performance indicator',
    'LMAO': 'laughing my [expletive] off',
    'NBD': 'no big deal',
    'OMG': 'oh my god',
    'POTUS': 'President of the United States',
    'Q&A': 'question and answer',
    'R&R': 'rest and relaxation',
    'SMH': 'shaking my head',
    'TMI': 'too much information',
    'V': 'very',
    'WYD': 'what you doing',
    'X': 'kiss',
    'BRB': 'be right back',
    'CIR': 'circulating',
    'DIY': 'do it yourself',
    'ETA': 'estimated time of arrival',
    'FAQ': 'frequently asked questions',
    'GR8': 'great',
    'ICYMI': 'in case you missed it',
    'JK': 'just kidding',
    'Kudos': 'congratulations',
    'L8': 'late',
    'MIA': 'missing in action',
    'NVM': 'never mind',
    'OOTO': 'out of the office',
    'PPL': 'people',
    'QOTD': 'quote of the day',
    'R&D': 'research and development',
    'SOP': 'standard operating procedure',
    'TGIF': "thank goodness it's Friday",
    'U': 'you',
    'VLOG': 'video blog',
    'WFH': 'work from home',
    'XOXO': 'hugs and kisses',
    'YOLO': 'you only live once',
    'ZOMG': 'oh my god',
    'ICYMI': 'in case you missed it',
    'NVM': 'never mind',
    'AC': 'air conditioning',
    'BTW': 'by the way',
    'COB': 'close of business',
    'DND': 'do not disturb',
    'EOD': 'end of day',
    'FYI': 'for your information',
    'GMTA': 'great minds think alike',
    'HBD': 'happy birthday',
    'IDK': "I don't know",
    'JIC': 'just in case',
    'KPI': 'key performance indicator',
    'LMAO': 'laughing my [expletive] off',
    'NBD': 'no big deal',
    'OMG': 'oh my god',
    'POTUS': 'President of the United States',
    'Q&A': 'question and answer',
    'R&R': 'rest and relaxation',
    'SMH': 'shaking my head',
    'TMI': 'too much information',
    'V': 'very',
    'WYD': 'what you doing',
    'X': 'kiss',
    'AMA': 'ask me anything',
    'B2C': 'business to consumer',
    'CU': 'see you',
    'DTRT': 'do the right thing',
    'EOM': 'end of message',
    'FUBAR': 'messed up beyond all recognition',
    'G2G': 'got to go',
    'HAGD': 'have a great day',
    'ICYMI': 'in case you missed it',
    'JIC': 'just in case',
    'KOTL': 'kiss on the lips',
    'L8R': 'later',
    'M8': 'mate',
    'NVM': 'never mind',
    'OMG': 'oh my god',
    'PPL': 'people',
    'Q4U': 'question for you',
    'ROFL': 'rolling on the floor laughing',
    'SRY': 'sorry',
    'TMI': 'too much information',
    'U2': 'you too',
    'V': 'very',
    'W8': 'wait',
    'XYL': 'ex-young lady (wife)',
    'YOLO': 'you only live once',
    'ZzZz': 'sleeping or bored',
    'BFFL': 'best friends for life',
    'CIR': 'cumulative incidence rate',
    'DIY': 'do it yourself',
    'EOD': 'end of day',
    'FAQ': 'frequently asked questions',
    'GTG': 'got to go',
    'ICYMI': 'in case you missed it',
     'JK': 'just kidding',
    'KPI': 'key performance indicator',
    'L8R': 'later',
    'MIA': 'missing in action',
    'NBD': 'no big deal',
    'OFC': 'of course',
    'PM': 'private message',
    'QOTD': 'quote of the day',
    'ROFL': 'rolling on the floor laughing',
    'SOS': 'save our souls',
    'TBA': 'to be announced',
    'TTYL': 'talk to you later',
    'U': 'you',
    'VLOG': 'video blog',
    'WTH': 'what the heck',
    'XOXO': 'hugs and kisses',
    'YMMV': 'your mileage may vary',
    'AFAIK': 'as far as I know',
    'B2W': 'back to work',
    'CM': 'call me',
    'DWBH': "don't worry, be happy",
    'EM': 'email',
    'F2F': 'face to face',
    'GFY': 'good for you',
    'HMU': 'hit me up',
    'IRL': 'in real life',
    'JOMO': 'joy of missing out',
    'LMAO': 'laughing my [expletive] off',
    'N/A': 'not applicable',
    'OFC': 'of course',
    'P2P': 'person to person',
    'QOTD': 'quote of the day',
    'ROFL': 'rolling on the floor laughing',
    'SMH': 'shaking my head',
    'TIA': 'thanks in advance',
    'U2': 'you too',
    'V': 'very',
    'WYD': 'what you doing',
    'XOXO': 'hugs and kisses',
    'YOLO': 'you only live once',
    'ZOMG': 'oh my god',
    'ICYMI': 'in case you missed it',
    'NVM': 'never mind',
    'BRB': 'be right back',
    'FAQ': 'frequently asked questions',
    'HBD': 'happy birthday',
    'JSYK': 'just so you know',
    'LMK': 'let me know',
    'OOTD': 'outfit of the day',
    'POS': 'parent over shoulder',
    'FYI': 'for your information',
    'IMO': 'in my opinion',
    'TMI': 'too much information',
    'L8R': 'later',
    'BFFL': 'best friends for life',
    'DIY': 'do it yourself',
    'EOD': 'end of day',
    'FOMO': 'fear of missing out',
    'GTG': 'got to go',
    'ICYMI': 'in case you missed it',
    'JK': 'just kidding',
    'KOTL': 'kiss on the lips',
    'L8R': 'later',
    'M8': 'mate',
    'NVM': 'never mind',
    'OMG': 'oh my god',
    'PPL': 'people',
    'Q4U': 'question for you',
    'ROFL': 'rolling on the floor laughing',
    'SRY': 'sorry',
    'TMI': 'too much information',
    'U2': 'you too',
    'V': 'very',
    'W8': 'wait',
    'XYL': 'ex-young lady (wife)',
    'YOLO': 'you only live once',
    'ZzZz': 'sleeping or bored',
    'BFFL': 'best friends for life',
    'CIR': 'cumulative incidence rate',
    'DIY': 'do it yourself',
    'EOD': 'end of day',
    'FAQ': 'frequently asked questions',
    'GTG': 'got to go',
    'ICYMI': 'in case you missed it',
    'JK': 'just kidding',
    'KPI': 'key performance indicator',
    'L8R': 'later',
    'MIA': 'missing in action',
    'NBD': 'no big deal',
    'OFC': 'of course',
    'PM': 'private message',
    'QOTD': 'quote of the day',
    'ROFL': 'rolling on the floor laughing',
    'SOS': 'save our souls',
    'TBA': 'to be announced',
    'TTYL': 'talk to you later',
    'U': 'you',
    'VLOG': 'video blog',
    'WTH': 'what the heck',
    'XOXO': 'hugs and kisses',
    'YMMV': 'your mileage may vary',
    'BFFL': 'best friends for life',
    'CIR': 'cumulative incidence rate',
    'DIY': 'do it yourself',
    'EOD': 'end of day',
    'FAQ': 'frequently asked questions',
    'GTG': 'got to go',
    'ICYMI': 'in case you missed it',
    'JK': 'just kidding',
    'KPI': 'key performance indicator',
    'L8R': 'later',
    'MIA': 'missing in action',
    'NBD': 'no big deal',
    'OFC': 'of course',
    'PM': 'private message',
    'QOTD': 'quote of the day',
    'ROFL': 'rolling on the floor laughing',
    'SOS': 'save our souls',
    'TBA': 'to be announced',
    'TTYL': 'talk to you later',
    'U': 'you',
    'VLOG': 'video blog',
    'WTH': 'what the heck',
    'YOLO': 'you only live once',
    'ZOMG': 'oh my god',
    'AFAICR': 'as far as I can remember',
    'B4N': 'bye for now',
    'CR8': 'create',
    'DIY': 'do it yourself',
    'EOD': 'end of day',
    'FTW': 'for the win',
    'G2G': 'got to go',
    'HAGD': 'have a great day',
    'ICYMI': 'in case you missed it',
    'J/K': 'just kidding',
    'KOTL': 'kiss on the lips',
    'L8R': 'later',
    'M8': 'mate',
    'NBD': 'no big deal',
    'OFC': 'of course',
    'PPL': 'people',
    'Q4U': 'question for you',
    'ROFL': 'rolling on the floor laughing',
    'SOS': 'save our souls',
    'TBA': 'to be announced',
    'TTYL': 'talk to you later',
    'U': 'you',
    'VLOG': 'video blog',
    'WTH': 'what the heck',
    'XOXO': 'hugs and kisses',
    'YOLO': 'you only live once',
    'ZOMG': 'oh my god',
    'ICYMI': 'in case you missed it',
    'NVM': 'never mind',
    'BRB': 'be right back',
    'FAQ': 'frequently asked questions',
    'HBD': 'happy birthday',
    'JSYK': 'just so you know',
    'LMK': 'let me know',
    'OOTD': 'outfit of the day',
    'POS': 'parent over shoulder',
    'FYI': 'for your information',
    'IMO': 'in my opinion',
    'TMI': 'too much information',
    'L8R': 'later',
    'BFFL': 'best friends for life',
    'DIY': 'do it yourself',
    'EOD': 'end of day',
    'FOMO': 'fear of missing out',
    'GTG': 'got to go',
    'ICYMI': 'in case you missed it',
    'JK': 'just kidding',
    'KOTL': 'kiss on the lips',
    'L8R': 'later',
    'M8': 'mate',
    'NVM': 'never mind',
    'OMG': 'oh my god',
    'PPL': 'people',
    'Q4U': 'question for you',
    'ROFL': 'rolling on the floor laughing',
    'SRY': 'sorry',
    'TMI': 'too much information',
    'U2': 'you too',
    'V': 'very',
    'W8': 'wait',
    'XYL': 'ex-young lady (wife)',
    'YOLO': 'you only live once',
    'ZzZz': 'sleeping or bored',
    'BFFL': 'best friends for life',
    'CIR': 'cumulative incidence rate',
    'DIY': 'do it yourself',
    'EOD': 'end of day',
    'FAQ': 'frequently asked questions',
    'GTG': 'got to go',
    'ICYMI': 'in case you missed it',
    'JK': 'just kidding',
    'KPI': 'key performance indicator',
    'L8R': 'later',
    'MIA': 'missing in action',
    'NBD': 'no big deal',
    'OFC': 'of course',
    'PM': 'private message',
    'QOTD': 'quote of the day',
    'ROFL': 'rolling on the floor laughing',
    'SOS': 'save our souls',
    'TBA': 'to be announced',
    'TTYL': 'talk to you later',
    'U': 'you',
    'VLOG': 'video blog',
    'WTH': 'what the heck',
    'XOXO': 'hugs and kisses',
    'YMMV': 'your mileage may vary',
    'BFFL': 'best friends for life',
    'CIR': 'cumulative incidence rate',
    'DIY': 'do it yourself',
    'EOD': 'end of day',
    'FAQ': 'frequently asked questions',
    'GTG': 'got to go',
    'ICYMI': 'in case you missed it',
    'JK': 'just kidding',
    'KPI': 'key performance indicator',
    'L8R': 'later',
    'MIA': 'missing in action',
    'cuming':'coming'
}

contractions_dict = {
    "ain't": "are not",
    "'s": "is",
    "aren't": "are not",
    "can't": "cannot",
    "can't've": "cannot have",
    "'cause": "because",
    "could've": "could have",
    "couldn't": "could not",
    "couldn't've": "could not have",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "hadn't": "had not",
    "hadn't've": "had not have",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd": "he would",
    "he'd've": "he would have",
    "he'll": "he will",
    "he'll've": "he will have",
    "how'd": "how did",
    "how'd'y": "how do you",
    "how'll": "how will",
    "I'd": "I would",
    "I'd've": "I would have",
    "I'll": "I will",
    "I'll've": "I will have",
    "I'm": "I am",
    "I've": "I have",
    "isn't": "is not",
    "it'd": "it would",
    "it'd've": "it would have",
    "it'll": "it will",
    "it'll've": "it will have",
    "let's": "let us",
    "ma'am": "madam",
    "mayn't": "may not",
    "might've": "might have",
    "mightn't": "might not",
    "mightn't've": "might not have",
    "must've": "must have",
    "mustn't": "must not",
    "dne":"done",
    "al":"all",
    "mustn't've": "must not have",
    "needn't": "need not",
    "needn't've": "need not have",
    "o'clock": "of the clock",
    "oughtn't": "ought not",
    "oughtn't've": "ought not have",
    "shan't": "shall not",
    "sha'n't": "shall not",
    "shan't've": "shall not have",
    "she'd": "she would",
    "she'd've": "she would have",
    "she'll": "she will",
    "she'll've": "she will have",
    "should've": "should have",
    "shouldn't": "should not",
    "shouldn't've": "should not have",
    "so've": "so have",
    "that'd": "that would",
    "that'd've": "that would have",
    "there'd": "there would",
    "there'd've": "there would have",
    "they'd": "they would",
    "they'd've": "they would have",
    "they'll": "they will",
    "they'll've": "they will have",
    "they're": "they are",
    "they've": "they have",
    "to've": "to have",
    "wasn't": "was not",
    "we'd": "we would",
    "we'd've": "we would have",
    "we'll": "we will",
    "we'll've": "we will have",
    "we're": "we are",
    "we've": "we have",
    "weren't": "were not",
    "what'll": "what will",
    "what'll've": "what will have",
    "what're": "what are",
    "what've": "what have",
    "when've": "when have",
    "where'd": "where did",
    "where've": "where have",
    "who'll": "who will",
    "who'll've": "who will have",
    "who've": "who have",
    "why've": "why have",
    "will've": "will have",
    "won't": "will not",
    "won't've": "will not have",
    "would've": "would have",
    "wouldn't": "would not",
    "wouldn't've": "would not have",
    "y'all": "you all",
    "y'all'd": "you all would",
    "y'all'd've": "you all would have",
    "y'all're": "you all are",
    "y'all've": "you all have",
    "you'd": "you would",
    "you'd've": "you would have",
    "you'll": "you will",
    "you'll've": "you will have",
    "you're": "you are",
    "you've": "you have"

}

df[['FirstPart', 'SecondPart']] = df['ColumnWithHeader'].str.split(n=1, expand=True)

my_dict = df.set_index('FirstPart')['SecondPart'].to_dict()


input_file_location = 'data.txt'

word_list = []

with open('data.txt', 'r', encoding='utf-8') as f:
    for line in f:
        for word in line.split():
            word_list.append(word.lower())

vocab = set(word_list)

word_count_dict = {}
word_count_dict = Counter(word_list)

probs = {}
total_words = sum(word_count_dict.values())

for word, word_count in word_count_dict.items():
    word_prob = word_count/total_words
    probs[word] = word_prob

def delete_letter(word):
    delete_list = []
    split_list = []
    split_list = [(word[:i], word[i:]) for i in range(len(word))]
    delete_list = [L+R[1:] for L, R in split_list]
    return delete_list

def switch_letter(word):
    switch_list = []
    split_list = []
    split_list = [(word[:i], word[i:]) for i in range(len(word))]
    switch_list = [L + R[1] + R[0] + R[2:] for L, R in split_list if len(R)>=2]
    return switch_list

def replace_letter(word):
    letters = 'abcdefghijklmnopqrstuvwxyz'
    replace_list = []
    split_list = []
    split_list = [(word[0:i], word[i:]) for i in range(len(word))]
    replace_list = [L + letter + (R[1:] if len(R)>1 else '') for L, R in split_list if R for letter in letters]
    replace_set = set(replace_list)
    replace_list = sorted(list(replace_set))
    return replace_list

def insert_letter(word):
    letters = 'abcdefghijklmnopqrstuvwxyz'
    insert_list = []
    split_list = []
    split_list = [(word[0:i], word[i:]) for i in range(len(word)+1)]
    insert_list = [L + letter + R for L, R in split_list for letter in letters]
    return insert_list

def edit_one_letter(word, allow_switches = True):
    edit_one_set = set()
    edit_one_set.update(delete_letter(word))
    if allow_switches: edit_one_set.update(switch_letter(word))
    edit_one_set.update(replace_letter(word))
    edit_one_set.update(insert_letter(word))
    if word in edit_one_set: edit_one_set.remove(word)
    return edit_one_set

def edit_two_letter(word, allow_switches = True):
    edit_two_set = set()
    edit_one = edit_one_letter(word, allow_switches=allow_switches)
    for word in edit_one:
        if word:
            edit_two = edit_one_letter(word, allow_switches=allow_switches)
            edit_two_set.update(edit_two)

    return edit_two_set

def get_spelling_suggestions(word, probs, vocab, n=1, default_probability=0.0):
    suggestions = (
        [word] if word in vocab else
        edit_one_letter(word).intersection(vocab) or
        edit_two_letter(word).intersection(vocab)
    )

    valid_suggestions = [s for s in suggestions if len(s) > 1]

    max_word = max(valid_suggestions, key=lambda s: probs.get(s, default_probability), default=None)

    if max_word:
        max_prob = probs.get(max_word, default_probability)
        return [[max_word, max_prob]]

    return []


default_probability = 0.0

result = get_spelling_suggestions("furthar", probs, vocab, 3, default_probability)

def correctSentence(sentence):

  contractions_re = re.compile('(%s)'%'|'.join(contractions_dict.keys()))
  def expand_contractions(s, contractions_dict=contractions_dict):
    def replace(match):
      return contractions_dict[match.group(0)]
    return contractions_re.sub(replace, s)
  sentence = expand_contractions(sentence)


  sent = word_tokenize(sentence)

  # sent = remove_punct(sent)

  listAns =[]
  for i in sent:
    if i in non_standard_word:
      listAns.append(non_standard_word[i])
    elif i in my_dict:
      listAns.append(my_dict[i])
    else:
      listAns.append(i)

  t = " ".join(listAns)

  final_sentence=""
  for w in t.split(' '):
    result = get_spelling_suggestions(w.lower(), probs, vocab, 3, default_probability)
    if(result):
      final_sentence+=result[0][0]+" "
    else:
      final_sentence+=w+" "
  # print(sentence)
  return final_sentence

# print(correctSentence("are you l8r"))


